import { Auth, Body, Controller, Get, HttpError, Params, Patch, Post, Returns, t, type RequestContext } from "adorn-api";
import { createFechamento, finalizeFechamento, getFechamento, listFechamentos, updateFechamento } from "../fechamento/fechamento-service.js";
import { FechamentoAtuarialDto, FechamentoAtuarialParamsDto, FechamentoAvaliacaoParamsDto, CriarFechamentoAtuarialDto, AtualizarFechamentoAtuarialDto } from "./fechamento-dtos.js";
const badRequest = (error: unknown): never => { throw new HttpError(400, error instanceof Error ? error.message : "Operação inválida."); };
@Auth() @Controller({ path: "/api", tags: ["Fechamento"] }) export class FechamentoController {
  @Get("/avaliacoes/:avaliacaoId/fechamentos") @Params(FechamentoAvaliacaoParamsDto) @Returns(t.array(t.ref(FechamentoAtuarialDto))) list(ctx: RequestContext<unknown, undefined, { avaliacaoId: number }>) { return listFechamentos(ctx.params.avaliacaoId); }
  @Post("/avaliacoes/:avaliacaoId/fechamentos") @Params(FechamentoAvaliacaoParamsDto) @Body(CriarFechamentoAtuarialDto) @Returns({ status: 201, schema: FechamentoAtuarialDto }) async create(ctx: RequestContext<CriarFechamentoAtuarialDto, undefined, { avaliacaoId: number }>) { try { return await createFechamento(ctx.params.avaliacaoId, ctx.body); } catch (error) { return badRequest(error); } }
  @Get("/fechamentos/:id") @Params(FechamentoAtuarialParamsDto) @Returns(FechamentoAtuarialDto) async get(ctx: RequestContext<unknown, undefined, { id: string }>) { const value = await getFechamento(ctx.params.id); if (!value) throw new HttpError(404, "Fechamento não encontrado."); return value; }
  @Patch("/fechamentos/:id") @Params(FechamentoAtuarialParamsDto) @Body(AtualizarFechamentoAtuarialDto) @Returns(FechamentoAtuarialDto) async update(ctx: RequestContext<AtualizarFechamentoAtuarialDto, undefined, { id: string }>) { try { return await updateFechamento(ctx.params.id, ctx.body); } catch (error) { return badRequest(error); } }
  @Post("/fechamentos/:id/finalizar") @Params(FechamentoAtuarialParamsDto) @Returns(FechamentoAtuarialDto) async finalize(ctx: RequestContext<unknown, undefined, { id: string }>) { try { return await finalizeFechamento(ctx.params.id); } catch (error) { return badRequest(error); } }
}
