import { useEffect, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import ArrowBackRounded from "@mui/icons-material/ArrowBackRounded";
import LockRounded from "@mui/icons-material/LockRounded";
import { api, type FechamentoAtuarial, type ResumoExecucaoCalculo } from "../../api/client";

function value(valueJson: string) { try { const item = JSON.parse(valueJson); return typeof item === "number" ? item.toLocaleString("pt-BR", { maximumFractionDigits: 2 }) : String(item); } catch { return valueJson; } }
export function FechamentoPage({ avaliacaoId, onBack }: { avaliacaoId: number; onBack: () => void }) {
  const [fechamentos, setClosings] = useState<FechamentoAtuarial[]>([]); const [runs, setRuns] = useState<ResumoExecucaoCalculo[]>([]); const [runId, setRunId] = useState(""); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null);
  const reload = async () => { const [nextClosings, nextRuns] = await Promise.all([api.fechamentos(avaliacaoId), api.execucoesCalculo(avaliacaoId)]); setClosings(nextClosings); setRuns(nextRuns.filter((run) => run.situacao === "CONCLUIDO")); setRunId((current) => nextRuns.some((run) => run.id === current && run.situacao === "CONCLUIDO") ? current : nextRuns.find((run) => run.situacao === "CONCLUIDO")?.id ?? ""); };
  useEffect(() => { void reload().catch((reason) => setError(reason instanceof Error ? reason.message : "Não foi possível carregar o fechamento.")).finally(() => setLoading(false)); }, [avaliacaoId]);
  const create = async () => { if (!runId) return; setWorking(true); setError(null); try { await api.criarFechamento(avaliacaoId, runId); await reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível iniciar o fechamento."); } finally { setWorking(false); } };
  const finalize = async (id: string) => { setWorking(true); setError(null); try { await api.finalizarFechamento(id); await reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível finalizar o fechamento."); } finally { setWorking(false); } };
  if (loading) return <Box sx={{ minHeight: 360, display: "grid", placeItems: "center" }}><CircularProgress size={28} /></Box>;
  return <Stack spacing={3}><Box><Button onClick={onBack} startIcon={<ArrowBackRounded />} sx={{ mb: 2 }}>Avaliação</Button><Typography variant="overline" color="text.secondary">Avaliação #{avaliacaoId}</Typography><Typography variant="h4">Fechamento Atuarial</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Reconcilia uma execução concluída e congela as métricas estruturadas que sustentam a rodada final.</Typography></Box>{error && <Alert severity="error">{error}</Alert>}<Paper elevation={0} sx={{ p: 2.5, border: "1px solid", borderColor: "divider" }}><Stack direction={{ xs: "column", md: "row" }} gap={2} alignItems={{ md: "center" }}><TextField select label="Cálculo concluído" value={runId} onChange={(event) => setRunId(event.target.value)} sx={{ minWidth: 360 }}>{runs.map((run) => <MenuItem key={run.id} value={run.id}>{run.versaoMotor} · {new Date(run.criadoEm).toLocaleString("pt-BR")}</MenuItem>)}</TextField><Button variant="contained" disabled={!runId || working} onClick={() => void create()}>Iniciar fechamento</Button></Stack>{runs.length === 0 && <Alert severity="warning" sx={{ mt: 2 }}>Execute um cálculo concluído antes de iniciar o fechamento.</Alert>}</Paper>{fechamentos.map((closing) => <Paper key={closing.id} elevation={0} sx={{ p: 3, border: "1px solid", borderColor: "divider" }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={2}><Box><Typography variant="h6">Rodada {closing.execucaoCalculoId.slice(0, 8)}</Typography><Typography variant="body2" color="text.secondary">Atualizado em {new Date(closing.atualizadoEm).toLocaleString("pt-BR")}</Typography></Box><Stack direction="row" gap={1}><Chip label={closing.situacao} color={closing.situacao === "FINALIZADO" ? "success" : "warning"} />{closing.situacao === "RASCUNHO" && <Button startIcon={<LockRounded />} disabled={working} onClick={() => void finalize(closing.id)}>Finalizar</Button>}</Stack></Stack><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2, minmax(0, 1fr))", lg: "repeat(3, minmax(0, 1fr))" }, gap: 1.5, mt: 2 }}>{closing.linhas.map((line) => <Box key={line.id}><Typography variant="body2" color="text.secondary">{line.rotulo}</Typography><Typography fontWeight={750}>{value(line.jsonValor)} {line.unidade ?? ""}</Typography><Typography variant="caption" color="text.disabled">{line.origem}</Typography></Box>)}</Box></Paper>)}</Stack>;
}
